# Phundament 4 - Application stack

php:
  build: .
  links:
    - 'mariadb:DB'

nginx:
  image: phundament/nginx-one:1.9
  links:
    - 'php:PHPFPM'

mariadb:
  image: 'tutum/mariadb:10.1'
  environment:
    MARIADB_PASS: secretadmin