<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use kartik\widgets\FileInput;

/**
* @var yii\web\View $this
* @var app\modules\templates\models\Template $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="panel panel-default">
    <div class="panel-heading">
                <?= $model->template_name ?>
    </div>

    <div class="panel-body">

        <div class="template-form">

            <?php $form = ActiveForm::begin([
                'id' => 'Template',
                'layout' => 'horizontal',
                'options' => [
                    'enctype' => 'multipart/form-data'
                ],
                'enableClientValidation' => true,
                'errorSummaryCssClass' => 'error-summary alert alert-error'
            ]
            );
            ?>

            <div class="">
                <?php $this->beginBlock('main'); ?>
                <div class="row">
                    <div class="col-md-4">
                        <p>
                            <p>&nbsp;</p>
                            <?= $form->field($model,'file')->widget(FileInput::classname(),[
                                'options' => [
                                    'accept' => '*'
                                ]
                            ]);
                            ?>
                        </p>
                    </div>
                    <div class="col-md-8">
                        <p>

                            <?= $form->field($model, 'id')->hiddenInput()->label(false) ?>
                            <?= $form->field($model, 'template_name')->textInput(['maxlength' => true]) ?>
                            <?php // $form->field($model, 'template_type')->textInput(['maxlength' => true]) ?>
                            <?= $form->field($model, 'is_active')->textInput() ?>
                            <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
                            $form->field($model, 'user_id')->dropDownList(
                                \yii\helpers\ArrayHelper::map(dektrium\user\models\User::find()->all(), 'id', 'username'),
                                ['prompt' => Yii::t('app', 'Select')]
                            ); ?>
                        </p>
                    </div>
                </div>

                <?php $this->endBlock(); ?>
                
                <?=
    Tabs::widget(
                 [
                   'encodeLabels' => false,
                     'items' => [ [
    'label'   => 'Template',
    'content' => $this->blocks['main'],
    'active'  => true,
], ]
                 ]
    );
    ?>
                <hr/>
                <?php echo $form->errorSummary($model); ?>
                <?= Html::submitButton(
                '<span class="glyphicon glyphicon-check"></span> ' .
                ($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save')),
                [
                    'id' => 'save-' . $model->formName(),
                    'class' => 'btn btn-success'
                ]
                );
                ?>

                <?php ActiveForm::end(); ?>

            </div>

        </div>

    </div>

</div>
